### ISSUE TITLE
[Issue]: rocThrust tries linking to CUDA headers on AMD system (Setonix at Pawsey)

### ISSUE THREAD

**Issue by fluidnumericsJoe** [ROCmSoftwarePlatform/rocThrust#442]
### Problem Description

```
OS:
NAME="SLES"
VERSION="15-SP4"
```
```
CPU: 
model name	: AMD EPYC 7A53 64-Core Processor
```
```
GPU:
  Name:                    AMD EPYC 7A53 64-Core Processor    
  Marketing Name:          AMD EPYC 7A53 64-Core Processor    
  Name:                    AMD EPYC 7A53 64-Core Processor    
  Marketing Name:          AMD EPYC 7A53 64-Core Processor    
  Name:                    AMD EPYC 7A53 64-Core Processor    
  Marketing Name:          AMD EPYC 7A53 64-Core Processor    
  Name:                    AMD EPYC 7A53 64-Core Processor    
```

I'm working on a project to port a code ( https://github.com/FluidNumerics/SegAlign/tree/hip_port) to AMD GPUs. When compiling the code, I am explicitly setting the CXX compiler to `hipcc`, e.g.

```
CXX=hipcc cmake -DCMAKE_BUILD_TYPE=Release \
      -DTBB_ROOT=${INTEL_TBB_ROOT} \
      -DBOOST_ROOT=${BOOST_ROOT} \
      -DCMAKE_HIP_ARCHITECTURES=gfx90a \
      -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
      -DCMAKE_INSTALL_PREFIX=${INSTALL_ROOT} \
      ..
make VERBOSE=1
```

During make, compilation fails with the following error
```
[ 11%] Building CXX object src/CMakeFiles/segalign.dir/__/common/seed_pos_table.cu.o
cd /scratch/pawsey0007/jschoonover/SegAlign/build/src && /software/setonix/rocm/5.7.3/bin/hipcc -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_NO_LIB -D__HIP_PLATFORM_AMD__=1 -D__HIP_PLATFORM_HCC__=1 -I/scratch/pawsey0007/jschoonover/SegAlign/common -I/scratch/pawsey0007/jschoonover/SegAlign/src -isystem /scratch/pawsey0007/jschoonover/software/segalign/include -isystem /scratch/pawsey0007/jschoonover/software/._segalign/dwlexrqtrontkcy7ledgiqzlxhoerppv/include -isystem /software/setonix/rocm/5.7.3/include -x c++ -DHIP_ENABLED -O3 -DNDEBUG -DTBB_SUPPRESS_DEPRECATED_MESSAGES -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -x hip -MD -MT src/CMakeFiles/segalign.dir/__/common/seed_pos_table.cu.o -MF CMakeFiles/segalign.dir/__/common/seed_pos_table.cu.o.d -o CMakeFiles/segalign.dir/__/common/seed_pos_table.cu.o -c /scratch/pawsey0007/jschoonover/SegAlign/common/seed_pos_table.cu
In file included from /scratch/pawsey0007/jschoonover/SegAlign/common/seed_pos_table.cu:7:
In file included from /software/setonix/rocm/5.7.3/include/thrust/scan.h:1656:
In file included from /software/setonix/rocm/5.7.3/include/thrust/detail/scan.inl:21:
In file included from /software/setonix/rocm/5.7.3/include/thrust/iterator/iterator_traits.h:62:
In file included from /software/setonix/rocm/5.7.3/include/thrust/iterator/detail/device_system_tag.h:23:
In file included from /software/setonix/rocm/5.7.3/include/thrust/system/cuda/detail/execution_policy.h:35:
/software/setonix/rocm/5.7.3/include/thrust/system/cuda/config.h:33:10: fatal error: 'cub/util_namespace.cuh' file not found
```

Tracking back through the header files for rocthrust, it appears that `THRUST_DEVICE_COMPILER` is not being set to `THRUST_DEVICE_COMPILER_HIP` ( in rocm/5.7.3/include/thrust/detail/config/compiler.h) and `THRUST_DEVICE_SYSTEM` is not being set to `THRUST_DEVICE_SYSTEM_HIP` (in rocm/5.7.3/include/thrust/detail/config/device_system.h). Manually editing these files to hard set these macros appropriately results in a successful build. 

I've also attempted to manually add the `-D__HIP__ -D__clang__` to the CXXFLAGS, but still encounter the same issue.

Note that I encounter the same error on another system with ROCm/6.1.2 (Ubuntu 22.04 with MI210 GPUs)

### Operating System

SLES 15-SP4, Ubuntu 22.04

### CPU

AMD EPYC 7A53 64-Core Processor

### GPU

AMD Instinct MI250X, AMD Instinct MI210

### ROCm Version

ROCm 6.1.0, ROCm 5.7.1

### ROCm Component

rocThrust

**Comment by Snektron** [comment]
It looks like rocThrust is getting confused by this definition of `__CUDACC__`: 
https://github.com/FluidNumerics/SegAlign/blame/d263619da1a8436ff8127277e710387f90efc5b3/common/gpu.h#L16

If I remove this part, everything seems to compile correctly on rocThrust 6.1.2.

**Comment by fluidnumericsJoe** [comment]
@Snektron - thanks for the quick response. I had pulled the example header from https://rocm.blogs.amd.com/software-tools-optimization/hipify/README.html (more specifically https://github.com/ROCm/rocm-blogs/blob/release/blogs/software-tools-optimization/hipify/src/gpu_macros.h ) and modified it for our use case.

I'll get that removed and give that a try. Glad it's likely a user error on my part :)

**Comment by fluidnumericsJoe** [comment]
Indeed this resolves this issue. Closing..
